### PR TITLE
Utf-8 email support3

### PR DESCRIPTION
**Pull request by edward-dauvergne**
Here are three preliminary commits for advancing the UTF-8 email support.

Regards,

Edward

### CODE REVIEW

**Comment by moy** [comment]
Thanks for the PR.

It seems you messed something with rebase. Also, this still does not pass pep8 check.

**Comment by edward-dauvergne** [comment]
The branch is messed up because I was following github's instructions at https://help.github.com/articles/syncing-a-fork/, and then used rebase to shorten the first line of the commit messages.  I guess I have to create a new branch and cherry-pick my way out of this mess.  For pep8, I see the message:

`# pep8 version: unavailable`

in both the master and my branch when running the tests.  I also see:
```
skipping test: pep8 git-multimail/git_multimail.py 
	pep8 "$D"/../"$f" --ignore=E402,E501,E123
    
ok 7 # skip pep8 git-multimail/git_multimail.py (missing pep8)

skipping test: pep8 t/test-env 
	pep8 "$D"/../"$f" --ignore=E402,E501,E123
    
ok 8 # skip pep8 t/test-env (missing pep8)
```
I don't understand.  Is the pep8 check new for testing UTF-8 in email address names?  Do I need to then get this master branch failing test to pass?  The logs don't seem to suggest this.  Also, when I run 'make' to execute the tests on master with less verbosity, everything passes except:

```
not ok 12 - Non-ascii characters in email (address part) # TODO known breakage
not ok 13 - Non-ascii characters in email (address part): content check # TODO known breakage
# still have 2 known breakage(s)
# passed all remaining 11 test(s)
```

**Comment by moy** [comment]
The simplest is probably to cherry-pick, yes. You can also `git reset --keep` to the latest commit of yours, and rebase the last commits on `origin/master` like `git rebase HEAD~4 --onto origin/master` or so. Or brute-force `git rebase origin/master`, and `git rebase --skip` all commits with conflicts.

You don't have pep8 installed so we skip the test. Best is to install pep8 (`pip install pep8` or your distro's package system). I had added a comment on GitHub on the commit introducing the breakage.

    test-env:41:10: E127 continuation line over-indented for visual indent
    test-env:43:10: E127 continuation line over-indented for visual indent

(You aligned the strings after the `u`, and pep8 doesn't like this. Your alignment is not particularly bad, but I want to keep the whole codebase PEP8 compliant, and adding an explicit exception would probably be more ugly than not doing this alignment)

When you submit a PR, travis-ci tells you whether the test pass.

**Comment by edward-dauvergne** [comment]
Ok, now I see the pep8 solution.  Maybe instead of just reporting "unavailable" in the first messages, it would be good to have "unavailable, please install with 'pip install pep8'".  The same with 'rstcheck'.

**Pull request closed without merging**
