### PR TITLE
New option to check tls server certificate

### PR DESCRIPTION
**Pull request by nononame**
- multimailhook.smtpCACerts

Signed-off-by: Simon P <simon.git@le-huit.fr>

### CODE REVIEW

**Comment by nononame** [comment]
http://marc.info/?t=146127574900003

**Comment by moy** [comment]
As noted by Travis, there are PEP8 and rstcheck issues with your patch. Please fix and force-push.

Thanks,

**Comment by moy** [comment]
What about the potential licensing issue noted by Michael Haggerty?

**Comment by nononame** [comment]
There is a GPLv3 on the secure-smtplib implementation: https://github.com/graingert/secure-smtplib
but I also found an older code equivalent to my patch under MIT license here: https://github.com/cybercase/django-smtp-starttls (code in django_smtp_starttls.py, licence in setup.py)

I think there is not problem to re-use MIT code.

**Comment by nononame** [comment]
a new pull-request with commit "sign-off" for continuous integration:
https://github.com/git-multimail/git-multimail/pull/151

**Comment by moy** [comment]
Thanks for the clarification about the license.

A hint: you don't have to close and open a new PR to change your commits, you can just `git push --force` into the existing branch. Opening a new PR is OK too, though.

Thanks,

**Comment by mhagger** [comment]
> I also found an older code equivalent to my patch under MIT license here

Thanks!

**Pull request closed without merging**
