### PR TITLE
Add a properly formatted Thread-Index mail header to make Outlook properly group by conversation (#192)

### LINKED ISSUE #192: Outlook doesn't show the mails as conversation
Either I just didn't find the right setting, or something is missing, so that outlook correctly considers the sent mails as a conversation like intended.
Currently they are only shown as individual messages, even if th "Show as conversations" checkbox is ticked in the "View" ribbon.
I guess for Outlook some other non-standard header is necessary, but I have no idea which.

### PR DESCRIPTION
**Pull request by Vampire**
Fixes #192

### CODE REVIEW

**Comment by Vampire** [comment]
After several force-pushes, my code is not working for Py2 and Py3.
The remaining failures seem to be not related to my changes.

**Comment by moy** [comment]
> After several force-pushes, my code is not working for Py2 and Py3.

It sometimes happens that the build breaks because of an upgrade on Travis or Pypi. In our case it seems pyflakes introduced new checks, and code that used to pass is now failing. I'll fix that and look at your PR.

**Comment by moy** [comment]
OK, actually: 1) you based your patch on an "old" commit. `master` still passes tests on latest Travis/Python. 2) you didn't update the expected result for most tests.

I've rebased your work and I'm fixing the tests. Should be OK soon.

**Comment by moy** [comment]
OK, rebasing on master creates weird side effects on this PR. I'm closing in favor of a new PR #194 .

**Comment by Vampire** [comment]
My commit should cleanly apply to master too, I did it here too.
I based my PR on the version I requested pull to, which is the 1.4 branch.
If you rebase but don't change the base branch it of course ends in strange result.

**Comment by moy** [comment]
This is a new feature, so it'll go to the next release, so I'll apply it to master. There was a very minor conflict going to master.

See my comment in the other PR, there's still work to do, but I'm almost there. New push very soon.

**Comment by Vampire** [comment]
i c, ok

**Comment by Vampire** [comment]
And regarding the test results, as Travis went through (besides the pyflakes things) I didn't think anything is not correct. I've seen this more as fix of threaded display than as new feature. :-D

**Pull request closed without merging**
