### PR TITLE
add option to show a graph of new commits in summary email

### PR DESCRIPTION
**Pull request by richardhansen**
This is a re-roll of pull request #77.  Rather than use the now-unsupported `--no-walk --graph` combination of arguments, it now uses the `git rev-list` arguments that are used to determine the set of new commits.  This required some infrastructure changes to enable code re-use.

Other changes:
  * mention the new feature in `CHANGES`
  * mention the new config options in `README`
  * remove the `--graph` example from `multimailhook.logOpts` in `README`
  * also show a graph of discarded commits now that I can trivially access the `git rev-list` arguments
  * rebase onto latest `master`

### CODE REVIEW

**Comment by moy** [comment]
Thanks. I started looking into the series, and already merged the first two patches, but I'm getting out of time for now.

One issue with the PR as-is: it really lacks a test. It is not hard to do, see the `t/` directory. Essentially, you have to add a few lines in `generate-test-emails`, run `./run-tests` and check the result.

**Comment by moy** [comment]
I've merged all preparatory commits with a few very minor changes. I rebased the last two ones in branch [showgraph-v2](https://github.com/git-multimail/git-multimail/tree/showgraph-v2).

I need a test before I can merge the result. Let me know if you really don't have time, I can do it myself if needed.

**Comment by richardhansen** [comment]
> We usually write docstrings and commit message with imperative tone, hence Returns -> Return. I've applied locally, you don't need to resend.

Thanks for fixing.  I prefer imperative tone too; I guess I spaced out.

> I've merged all preparatory commits with a few very minor changes. I rebased the last two ones in branch showgraph-v2.

Thank you!

> I need a test before I can merge the result. Let me know if you really don't have time, I can do it myself if needed.

Thank you for offering!  I don't mind writing some tests, though it may take me a few days to get around to it.  (I'm in no hurry to get this merged, so feel free to let the pull request sit for a while with an incomplete tag.)

**Comment by moy** [comment]
Just a ping ;-). I'll try to get a 1.1 release in June. If you manage to complete this PR soon, that would be perfect!

Thanks,

**Comment by richardhansen** [comment]
Apologies—I have a work deadline this weekend.  I should be able to get to this early next week.

**Comment by moy** [comment]
Actually, I think I'll finish this today unless you object (soon).

**Comment by moy** [comment]
OK, it's done in 1348e58ad21a8326354f167de44168fec411752d and 7928201f4d8684c1ef9c00713c775de74015ba26. Note that you broke compatibility with old Python versions (I'd like to keep 2.4 compatibility at least for the next release), but it's repaired. Thanks for your patches, and keep contributing in the future :-).

**Comment by richardhansen** [comment]
Thank you for merging!

**Pull request closed without merging**
