### PR TITLE
Html colored email for diffs

### PR DESCRIPTION
**Pull request by marcmengel**
So here is a change to  allow you to have colored html diffs in your diff emails.  I tried to limit it entirely to a mixin class, but I had to add a little bit of code to the email level that adds some line break tags
if we're sending text/html mail, because of course the whole email message is html or not, not just the diff itself.

### CODE REVIEW

**Comment by DanielCeregatti** [comment]
I've given this a shot and I can't get it to work. I've set multimailhook.dohtmldiffs = True, even hard coded dohtmldiffs = True in the script. It seems that nothing invokes the code blocks where all this happens.

I'll play with this some more and report back if I make any progress.

**Comment by DanielCeregatti** [comment]
Never mind. It seems there are other issues with the main code, not just this pull request, so I decided to go with https://github.com/nacho/email-hook. Worked perfectly out of the box and does colored diffs.

**Comment by moy** [comment]
What are the "other issues" with the code? I'm happy to see that there are alternatives (I didn't know email-hook), but it would be nice to fix git-multimail too if there's anything we can fix.

Thanks,

**Comment by moy** [comment]
@marcmengel: Thanks for the patch. But would you please add a `Signed-off-by` line to the commit, indicating your acceptance of the license [in the manner of the Git project](https://github.com/git/git/blob/9532ead9875b7b92ff2007f9de61af5874e8839a/Documentation/SubmittingPatches#L234)? Feel free to force-push to your branch with the fixed commit. Thanks!

(Also, sorry for the delay in answers, we're not terribly responsive these days ...)

**Comment by moy** [comment]
Ping: don't forget to sign-off your commits if you want the PR to be merged. Thanks,

**Comment by moy** [comment]
@marcmengel: Ping: don't forget to sign-off your commits if you want the PR to be merged. I'll close it otherwise.

Thanks.

**Comment by moy** [comment]
No sign-off, and an alternative implementation has been merged => I'm closing the PR.

**Pull request closed without merging**
