### PR TITLE
Atlassian stash plugin

### PR DESCRIPTION
**Pull request by newren**
This pull request includes 5 commits from pull request #52 (email for only a subset of refs) and 1 from pull request #53 (StashEnvironment), because it builds on the StashEnvironment.  The relevant commits for this pull request are the 5 at the end.

These five commits provide the source for an Atlassian Stash Plugin, which adds various GUI configuration knobs and such to the webpage for the local stash instance, as well as hooking up git_multimail to the relevant Stash specific hook.  (While Stash can use normal git post-receive hooks, there are two problems with doing so: (1) merges of pull requests are done on the server and hence bypass those, (2) those hooks don't have access to the correct username of the pusher nor the user-visible repository name that is involved.)

This pull-request is probably not quite ready to be merged as there are a few things we're fixing up locally.  We could fix those in subsequent pull requests, but the biggest question right now for me is whether the glue for hooking Stash up to git-multmail (i.e. this Atlassian Stash Plugin) even makes sense to include as part of git-multimail, or whether that glue belongs in its own separate project.

### CODE REVIEW

**Comment by moy** [comment]
I have mixed feelings about including this in git-multimail. I'm not an Atlassian Stash user, so I cannot test, and I can't even review it efficiently because I don't know the Stash API. I consider merging code as a (possibly weak) promise to maintain it afterwards, and I can't make this promise at the moment.

OTOH, having an all-in-one ready to use package to plug git-multimail into Stash may be nice for Stash users.

I'd say that a prerequisite to merge would be that someone (@newren?) steps-in as a subsystem maintainer.

Another option is to reverse the dependency: have the Stash plugin in a separate repo, but let the plugin download `git_multimail.py` automatically on install or so. If there's an easy technical way to do this, that would be the best option to me.

**Comment by newren** [comment]
Stash plugins, the most straightforward way I know to write them, have internal storage for their settings (per repo) and provide automagic REST API end points and such for modifying them.  It was certainly easiest to just keep the values there and pass them via command line flags to git-multimail, and perhaps there are technical challenges to trying to grab the values from the config for the REST API, though maybe I was just being excessively lazy not trying make sure these values were also stored in the local git config file of the relevant repo.  I'll look into it.

Also, reversing the dependency and having git-multimail as a submodule seems fine.

**Comment by moy** [comment]
Nice to see you back!

About command-line arguments, another option would be to allow

    git-multimail.py -c multimailhook.foo=bar

just like

    git -c config.option=value

to set an arbitrary Git configuration value. Internally, this basically sets an environment variable so it should be rather easy to implement. That would solve once and for all the problem of CLI options Vs Config options.

**Comment by newren** [comment]
Ooh, I like the -c option idea.  Let me take a look at that.

**Comment by moy** [comment]
In `git`, the `-c` option works by setting the environment variable `GIT_CONFIG_PARAMETERS` (an environment variable is needed because not all Git commands are builtin). For example,

    git -c foo.bar=boz -c x.y=z\' 

will set:

    GIT_CONFIG_PARAMETERS='foo.bar=boz' 'x.y=z'\'''

**Comment by moy** [comment]
BTW, one way to use `-c` without modifying `git_multimail.py` is to rename it like `git-multimail`, put in in your `$PATH` or Git's exec-path, and run `git -c foo.bar=boz multimail`. But that's not really convenient: in a typical installation, I don't have `git_multimail.py` in my $PATH and I hardcode its path in the hook.

**Comment by moy** [comment]
OK, I'm tagging this "not-for-merge" as reversing the dependency from stash plugin to `git_multimail.py` seems the way to go. I'm keeping this open as a reminder that there's something to be done though.

**Comment by moy** [comment]
The `git-multimail -c` idea is now in issue #102, so I think no more action is needed on my side for this PR. @newren : Can I close it?

**Comment by moy** [comment]
No news => I'm closing the PR. Feel free to add comments and reopen if needed.

**Pull request closed without merging**
