### PR TITLE
with gitolite, try getting From address from gitolite.conf

### PR DESCRIPTION
**Pull request by richardhansen**
Add `GitoliteEnvironmentMixin.get_fromaddr()` that reads the name and address from the `gitolite.conf` file.  If the name and email aren't found there, pass responsibility on to the next mixin/base class.

This function expects a specially formatted block of comments in `gitolite.conf` that looks like this:

    # BEGIN USER EMAILS
    # username Firstname Lastname <email@example.com>
    # END USER EMAILS

### CODE REVIEW

**Comment by richardhansen** [comment]
Thank you for [reviewing](https://github.com/richardhansen/git-multimail/commit/7e487d1be6ddd1938bcb180d4b967d8e6037946a)!

I just pushed a reroll that has the following changes:

  * reword the commit message for 3515997 and add some links to web pages describing Python's resolution order algorithm
  * use a loose regex to match BEGIN/END USER EMAILS, as suggested
  * use a looser regex to match the user entry, as suggested
  * add some documentation to README, as suggested
  * add a comment explaining the `GL_ADMINDIR` and `GL_CONF` variables
  * rebase onto latest master

I believe it is now ready to merge.

> Can you clarify how and in what order things are looked for in the end? Which one takes precedence over which?

The order comes from Python's Method Resolution Order (MRO) algorithm, which is [C3 linearization](https://en.wikipedia.org/wiki/C3_linearization).  (Also see the article "[The Python 2.3 Method Resolution Order](https://www.python.org/download/releases/2.3/mro/)".)  Python enumerates all of the ancestor classes (including the class itself) all the way back to `object` in a particular order, then searches this list for the desired method/attribute.  The C3 algorithm is a bit hard to describe concisely, but in a nutshell, mixins listed earlier get priority over mixins listed later.

You can examine the `__mro__` class attribute to see the actual order:

    import git_multimail
    from pprint import pprint
    pprint(git_multimail.GenericEnvironment.__mro__)
    pprint(git_multimail.GitoliteEnvironment.__mro__)

The above produces:

    (<class 'git_multimail.GenericEnvironment'>,
     <class 'git_multimail.ProjectdescEnvironmentMixin'>,
     <class 'git_multimail.ConfigMaxlinesEnvironmentMixin'>,
     <class 'git_multimail.ComputeFQDNEnvironmentMixin'>,
     <class 'git_multimail.FQDNEnvironmentMixin'>,
     <class 'git_multimail.ConfigFilterLinesEnvironmentMixin'>,
     <class 'git_multimail.ConfigRecipientsEnvironmentMixin'>,
     <class 'git_multimail.PusherDomainEnvironmentMixin'>,
     <class 'git_multimail.ConfigOptionsEnvironmentMixin'>,
     <class 'git_multimail.ConfigEnvironmentMixin'>,
     <class 'git_multimail.MaxlinesEnvironmentMixin'>,
     <class 'git_multimail.FilterLinesEnvironmentMixin'>,
     <class 'git_multimail.StaticRecipientsEnvironmentMixin'>,
     <class 'git_multimail.GenericEnvironmentMixin'>,
     <class 'git_multimail.Environment'>,
     <type 'object'>)
    (<class 'git_multimail.GitoliteEnvironment'>,
     <class 'git_multimail.ProjectdescEnvironmentMixin'>,
     <class 'git_multimail.ConfigMaxlinesEnvironmentMixin'>,
     <class 'git_multimail.ComputeFQDNEnvironmentMixin'>,
     <class 'git_multimail.FQDNEnvironmentMixin'>,
     <class 'git_multimail.ConfigFilterLinesEnvironmentMixin'>,
     <class 'git_multimail.ConfigRecipientsEnvironmentMixin'>,
     <class 'git_multimail.PusherDomainEnvironmentMixin'>,
     <class 'git_multimail.ConfigOptionsEnvironmentMixin'>,
     <class 'git_multimail.ConfigEnvironmentMixin'>,
     <class 'git_multimail.MaxlinesEnvironmentMixin'>,
     <class 'git_multimail.FilterLinesEnvironmentMixin'>,
     <class 'git_multimail.StaticRecipientsEnvironmentMixin'>,
     <class 'git_multimail.GitoliteEnvironmentMixin'>,
     <class 'git_multimail.Environment'>,
     <type 'object'>)

Once Python has this linear list of classes, it goes through them one by one until it finds one that both defines the method and doesn't use `super()`.  The `super()` function tells Python to continue to the next class in the list.  Without the call to `super()`, Python stops its search.

**Comment by richardhansen** [comment]
Apologies, @moy:  I'm not used to GitHub—I wasn't expecting a force push to hide your review comments on my original commits.  In the future I'll push a new branch, submit a new pull request, and close the old pull request.

I could try to restore the original commits on this pull request and then open a new pull request referencing this one, but I'm not sure if that would make things worse or not.

**Comment by moy** [comment]
Thanks a lot for your explanations. I'm not very much used to GitHub either, but it's OK for me to force-push if you took my comments into account.

If I understand correctly, if I comment on commits, my comments get lost by force-push, but if I comment on the "Files changed" tab of the PR, GitHub will detect when the comments are obsolete and mark them as "... commented on an obsolete patch" or so.

Thanks, I'll review it one last time and merge it ASAP.

**Comment by moy** [comment]
I rebased and merged your code. Tested and approved, thanks!

While I was there, I also added a gitolite-specific documentation.

**Pull request closed without merging**
