### PR TITLE
[RFC] Preliminary Python3 support

### PR DESCRIPTION
**Pull request by moy**
Hi,

I've worked on Python 3 support for git-multimail. Currently, the script itself is not portable, but the result of `2to3` passes the testsuite in Python 3.

Eventually, git_multimail3.py will replace git_multimail.py, but it's hard to keep Python 2.4 portability (git_multimail.py currently works on this prehistoric version of Python ...), so I plan to keep both for some time.

I'm not 100% happy with the results, hence the RFC status of this PR. Any Python 3 expert (or not) to comment?

### CODE REVIEW

**Comment by edward-dauvergne** [comment]
I have ported my [own software relax](http://www.nmr-relax.com) to use both Python 2 and 3.  Using the 2to3 script should be taken with a grain of salt, as some of its conversions are ugly and not Python 2 compatible.  I use it for [some conversions and for continual code auditing](http://svn.gna.org/viewcvs/relax/trunk/docs/devel/2to3_checklist?view=markup).  In the end I created a [compat module](http://svn.gna.org/viewcvs/relax/trunk/lib/compat.py?view=markup) for cleanly handling all Python versions, so maybe something similar could be used (I gave up on Python 2.4 because of import issues with using `from __future__ import absolute_import`, but git-multimail would not suffer from this).  The licence is GPLv3+, so copying code to GPLv2+ git-multimail may not be possible.  But the solutions in this compat module might help inspire clean solutions for git-multimail.

**Comment by moy** [comment]
I want to keep Python 2.4 compatibility for a while (I have an actual use-case for it, and I think I should use the latest version for my own needs as much as possible to get as much real-life tests as possible), so I would prefer not using __future__ for now.

That said, the result of 2to3 seems to be compatible with Python 2.6 (I didn't run the whole testsuite, but a trivial manual test worked), so once we drop support for Python < 2.6, we probably won't even need a compatibility module (well, the `if PYTHON3:` statements in the code can be moved to separate functions but that would be rather trivial).

The complete diff from `git_multimail.py` to `git_multimail3.py` is actually rather short, essentially exception handlers and `x.next()` Vs `next(x)`.

```
1c1
< #! /usr/bin/env python2
---
> #! /usr/bin/env python3
508c508
<         except CommandError, e:
---
>         except CommandError as e:
554c554
<         except CommandError, e:
---
>         except CommandError as e:
648c648
<         return iter(generate_summaries('--no-walk', self.sha1)).next()
---
>         return next(iter(generate_summaries('--no-walk', self.sha1)))
656c656
<     def __nonzero__(self):
---
>     def __bool__(self):
743c743
<             except KeyError, e:
---
>             except KeyError as e:
1782c1782
<         except OSError, e:
---
>         except OSError as e:
1792c1792
<         except Exception, e:
---
>         except Exception as e:
1862c1862
<         except Exception, e:
---
>         except Exception as e:
1880c1880
<             if isinstance(to_addrs, basestring):
---
>             if isinstance(to_addrs, str):
1883c1883
<         except Exception, e:
---
>         except Exception as e:
2645c2645
<         except Exception, e:
---
>         except Exception as e:
2663c2663
<             except Exception, e:
---
>             except Exception as e:
2818c2818
<     def next(self):
---
>     def __next__(self):
3220c3220
<                 extra_values = {'send_date': send_date.next()}
---
>                 extra_values = {'send_date': next(send_date)}
3253c3253
<                     extra_values = {'send_date': send_date.next()}
---
>                     extra_values = {'send_date': next(send_date)}
3618c3618
<     except ConfigurationException, e:
---
>     except ConfigurationException as e:
```

**Comment by edward-dauvergne** [comment]
There's zero need for `future` imports in git-multimail, as there are no packages.  With the command:

```sh
2to3 -j 4 -w -f apply -f basestring -f buffer -f callable -f dict -f except -f exec -f execfile -f exitfunc -f filter -f funcattrs -f future -f getcwdu -f has_key -f idioms -f import -f imports -f imports2 -f input -f intern -f isinstance -f itertools -f itertools_imports -f long -f map -f metaclass -f methodattrs -f ne -f next -f nonzero -f numliterals -f operator -f paren -f raise -f raw_input -f reduce -f renames -f repr -f set_literal -f standarderror -f sys_exc -f throw -f tuple_params -f types -f unicode -f urllib -f ws_comma -f xrange -f xreadlines -f zip .
```

I also see the change:

```diff
@@ -80,7 +80,7 @@ ZEROS = '0' * 40
 LOGBEGIN = '- Log -----------------------------------------------------------------\n'
 LOGEND = '-----------------------------------------------------------------------\n'
 
-ADDR_HEADERS = set(['from', 'to', 'cc', 'bcc', 'reply-to', 'sender'])
+ADDR_HEADERS = {'from', 'to', 'cc', 'bcc', 'reply-to', 'sender'}
 
 # It is assumed in many places that the encoding is uniformly UTF-8,
 # so changing these constants is unsupported.  But define them here
```

Both the `set()` and `{}` syntax work in both Python 2 and 3 (but the later not in Python 2.4, so it shouldn't change).  The other changes are perfectly fine on all Python versions > 2.5.  However the `except XyzError as e:` changes will not work in Python 2.4 (so I avoided these 100%).  Instead, the `sys.exc_info()` call can be used.  For example from my compat module:

```Python
try:
    import bz2
    from bz2 import BZ2File
    bz2_module = True
except ImportError:
    BZ2File = object
    bz2_module = False
    message = sys.exc_info()[1]
    bz2_module_message = message.args[0]
```

For most instances, this will work.  But for those that access the Exception's retcode variable, I'm not sure what to do there.

**Comment by moy** [comment]
> There's zero need for future imports in git-multimail, as there are no packages.

I agree with the conclusion, but not with the reason: `__future__` imports are useful if you use `print` and integer division for example. But fortunately, we don't ;-).

>  Instead, the sys.exc_info() call can be used.

I did find the `exec_info` thing when googling for Python 2/3 compatibility, but I'd rather avoid polluting the code with compatibility stuff. The long-term solution is the Python 3 syntax, and it will work on Python 2.6/2.7 too. I want to keep 2.4 compatibility for a while, but not forever.

**Comment by edward-dauvergne** [comment]
The use of Exception information function `sys.exc_info()` is not so bad ([see the Python docs](https://docs.python.org/2/library/sys.html#sys.exc_info)).  It has stayed constant between Python 1.5 and 3.5 (I have a testing setup with all minor versions from Python 1.0 onwards).  I doubt it will ever change, even beyond Python4, so it should be very future-proof.  It is far more stable than the error catching constructs and as an interface it is quite clean.  For example to access all parts of the Exception robustly in all Python versions > 1.4, just use:

```Python
except:
    type, value, traceback = sys.exc_info()
```

The string representation of `value` is the final error message, which is what git-multimail uses in almost all cases (the retcode being the exception).

**Comment by moy** [comment]
My concern is not being future-proof, but readability.

**Comment by edward-dauvergne** [comment]
Using this construct, some code would change as:

```Python
        except Exception as e:
            sys.stderr.write(
                '*** Error while generating commit email\n'
                '***  - mail sending aborted.\n'
                )
            try:
                # subprocess.terminate() is not available in Python 2.4
                p.terminate()
            except AttributeError:
                pass
            raise e
```
to:

```Python
        except:
            sys.stderr.write(
                '*** Error while generating commit email\n'
                '***  - mail sending aborted.\n'
                )
            try:
                # subprocess.terminate() is not available in Python 2.4
                p.terminate()
            except AttributeError:
                pass
            raise
```

Or:
```Python
        except Exception as e:
            sys.stderr.write(
                '*** Error establishing SMTP connection to %s ***\n'
                % self.smtpserver)
            sys.stderr.write('*** %s\n' % str(e))
            sys.exit(1)
```
to:
```Python
        except:
            sys.stderr.write(
                '*** Error establishing SMTP connection to %s ***\n'
                % self.smtpserver)
            sys.stderr.write('*** %s\n' % sys.exc_info()[1])
            sys.exit(1)
```

One last example:
```Python
        except Exception as e:
            raise ConfigurationException(
                'Invalid Ref Filter Regex "%s": %s' % (ref_filter_regex, e.message))
```
to:
```Python
        except:
            raise ConfigurationException(
                'Invalid Ref Filter Regex "%s": %s' % (ref_filter_regex, sys.exc_info()[1]))
```

So the `except` part is simplified, but the error message extraction part is not (though it would force a standardisation of `str(e)` and `e.message` to `sys.exc_info()[1]`).

**Comment by moy** [comment]
OK, it's not as bad as I thought. So it's probably feasible to change the Python 2 code until `2to3` has nothing to do and get a fully portable script.

No time to work on this for now, though.

**Comment by moy** [comment]
Pushed a new version that gets rid of 2to3. It fails the tests on travis for the "PR" build (which is basically a non-ff merge with master), but I can't reproduce the failure on my machine :-(. It's due to 00-sanity.t calling git-multimail on the repository itself (not a test repo), and it doesn't like the merge commit in Python3. I'm tempted to ignore the failure ... (we do need more encoding-related tests though, see #124 for example).

**Comment by moy** [comment]
OK, we still have the travis failure on 'pr', but I'm still merging the PR:
* This will help checking that future changes do not introduce new Python 3 breakage
* We do need more encoding-related tests, so hopefully we'll re-discover this failure later
* I can't reproduce locally, so I can't debug.

**Pull request merged**
